### ISSUE TITLE
[버전 다운그레이드] 스프링 부트 3.0에서의 스프링 시큐리티 설정 변경으로 인한 다운그레이드 요청

### ISSUE THREAD

**Issue by kkssbbb** [Teeeeeeeam/RecipeRadar#1]
## 현황

스프링 3.0 부터 변화된 스프링 시큐리티 설정 변화들로인한 이슈 발생

## 요청 사항

스프링 3.0 부터 바뀐 스프링시큐리티 설정들로인해 어떤 이슈가 발생할지몰라 2.x 으로 다운그레이드

### 변경된 내용

- (여기에 변경된 스프링 부트 3.0에서의 스프링 시큐리티 설정 내용 추가)

### 계획
다른 팀원 분들 의견 필요

**Comment by kkssbbb** [comment]
커밋 이슈 링크달기 관련 내용 아래 링크 참고해서 다운그레이드하고 커밋날릴떄 이슈링크달아서 이슈 닫아주면 될꺼같아요! @CHISANW 
- https://www.lesstif.com/gitbook/github-push-pr-pull-request-issue-129008869.html

**Comment by CHISANW** [comment]
@kkssbbb  알겠습니다!
